# Generated by Django 3.1.5 on 2021-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManage', '0002_auto_20210224_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumers',
            name='address',
            field=models.CharField(max_length=50, verbose_name='The address'),
        ),
    ]
